services:
  mongodb:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: cashsnowshopdata
      MONGO_INITDB_ROOT_PASSWORD: thisispasswordforsnowshopdata
volumes:
  mongodb-data:
